rcomp:
	javac my_Reverse.java 

rrun:
	java my_Reverse

redit:
	vim my_Reverse.java

ledit:  
	vim node.java list.java main.java

lcomp:
	javac node.java list.java main.java

lrun:
	java main

clean:
	rm -v *.class
