######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 26 17:03:35 2007
######################################################################

TEMPLATE = app
TARGET =  main
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += business.h calendar.h contacts.h mainwidget.h meeting.h personal.h
FORMS += main.ui
SOURCES += calendar.cc contacts.cc main.cc mainwidget.cc meeting.cc
