							PREFACE

This is a book about the computer language called C. If you are
seeking a book to increase your typing speed, expand on your
knowledge of word processing, or learn the secrets of chip
fabrication and design, this is not the one for you. However , if
you want to become thoroughly familiar with the C programming
language, then you have made a wise choice. For this book is devoted
to just that--to help you become proficient in C.

	It is one thing to read about a language; it is quite another to
get involved in it.. The best and most time-effective way to absorb
a language such as C is to have 1 terminal or computer available to
you , preferably at you fingertips. You will be exposed  to well
over 100 C programs in this book.

	You are encouraged to experiment with the programs illustrated
in this text. Omit keywords, change a comma to a period, ,
deliberately forget to terminate a statement with the required
semicolon, etc. You can do whatever you want without having to worry
about causing any damage to the computer, because you simply can't.
Play "what if" games to your heart's content. Familiarity with the
language will bring with it greater understanding ;the more you
understand about "C", the more you will enjoy it. ???
