######################################################################
# Automatically generated by qmake (2.00a) Sat Dec 2 17:55:22 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwidget.h
FORMS += form.ui
SOURCES += main.cc mainwidget.cc
